GET http://localhost:8080/hello

###
POST http://localhost:8080/hello
Content-Type: application/json

{
  "name": "vertx"
}

###

GET http://localhost:9091/a/hello?x=1

###
POST http://localhost:9091/hello
Content-Type: application/json

{
  "name": "bilibili"
}

###
